### ISSUE TITLE
Create a project of user interface

### ISSUE THREAD

**Issue by esesyn01** [Mini-air-quality-station/issues#13]
**Goal of the task:**

Create a project of user interface that will be placed in target device in order to make it easier to implement
UI.

**What functionality will it affect?**

docs, sensors-and-screen

**Scope of the task:**

Create a project of user interface, which will be displayed on a screen, assuming it will be handled using tact switches.

**Resources and tips:**

**Definition of Done:**

PR to docs

**Comment by iwanicki92** [comment]
@esesyn01 Is this duplicate of #23?
If it is then it should probably be closed as a duplicate.
