### ISSUE TITLE
Add required modules and packages to the Yocto image

### ISSUE THREAD

**Issue by punfil** [Mini-air-quality-station/issues#18]
**Goal of the task:**
Add required modules and packages to the Yocto image

**What functionality will it affect?**
web-server implementation
meta-air-quality implementation

**Scope of the task:**
Add required modules and packages to the Yocto image:
apache2 web server
visualization library
database software

**Resources and tips:**
Google

**Definition of Done:**
PR merged to main in meta-air-quality repo with all necessary modules and packages.

**Comment by punfil** [comment]
@esesyn01 I understand that responsibility for merging new packages has been shifted?

**Comment by esesyn01** [comment]
@punfil Yes, this issue is a part of this task - https://github.com/Mini-air-quality-station/issues/issues/30
