### ISSUE TITLE
Power source and monitoring battery level research

### ISSUE THREAD

**Issue by esesyn01** [Mini-air-quality-station/issues#21]
**Goal of the task:**

The goal of this task is to do a research of a best solution to power the device and monitor the battery level.

**What functionality will it affect?**

sensors-and-screen, documentation

**Scope of the task:**

- Choose the best option for power souirce (power bank, accumulator) - check the prices, power capacity and the charging speed.
- Examine how the battery level can be monitored: directly from the power source, maybe additional devices
- Update the device circuit if needed

**Resources and tips:**

**Definition of Done:**

- Comment with short summary of the best option
- PR with changes to device circuit, if any

**Comment by iwanicki92** [comment]
# Power source and charge monitoring

Used power bank should have pass-through capability so it can be charged and power the device simultaneously.
Without pass-through we would need some kind of power multiplexer(i.e. TPS2116) that chooses either USB power or power bank output depending which is available.
Cost of Power MUX IC is around 5-15 zł.

I assumed that we will use our own power bank. Buying new one could cost way over 100 zł.

We will need to measure how much power our device uses but with 10 000 mAh power bank we will probably get between 10-50 hours of operating time.

1. **Power bank, charge approximation**

Charge would need to be calculated based on time from last charging and how for how long device was charged.
Most likely accuracy of calculations will go down with time.
Assuming there is no voltage on VCC input pin of power bank we could connect it to one of GPIO pins to detect charger.
We would need to experimentally check how long it takes to completely drain and charge power bank.

![obraz](https://user-images.githubusercontent.com/103502689/227777936-daadcf4f-df30-486d-a570-b0a818ad4330.png)

**Needed**:
Power bank
Either 2 resistors, step-down converter or logic level converter.
2x female USB connector for external USB and power bank connection
**Cost**:
Resistors – around 1-2 zł for 30 resistors or step-down/logic level converter – 10-15 zł.
USB connectors – 2-5 zł.

2. **Power bank, voltage level monitoring**

We could estimate charge level based on voltage level of power bank batteries.
This method is very accurate for charge levels above 90% and below 20%.
When battery is between 20% and 90% accuracy could be increased by similar approximation as in first option.
**Needed**:
Power bank that we can open
ADC – analog-to-digital converter
**Cost**:
ADC – 10-30 zł

3. **Li-po battery, voltage level monitoring**

Monitoring charge level would be the same as in second option, but we would need li-po battery which could cost over 150 zł for 10000 mAh battery.
We would also need battery charging module which would cost about 10-30 zł.

4. **Conclusion**

In my opinion second option would be most accurate and quite easy to implement.
In case we don’t have power bank that we could open then we should go with first option.
Third option would cost too much, same with buying new power bank.
I will do more detailed research after we decide which option should we go with.
I will also need more information about which power bank we will use as my own has no pass-through capability and is not openable.
