### ISSUE TITLE
Implement the interface

### ISSUE THREAD

**Issue by esesyn01** [Mini-air-quality-station/issues#24]
**Goal of the task:**

Implement the interface from the concept graphics.

**What functionality will it affect?**

sensors-and-screen

**Scope of the task:**

**Resources and tips:**

**Definition of Done:**

- PR with changes to sensor and screen

**Comment by ola567** [comment]
A comment to save gained knowledge: According to Michał Iwanicki the library, which can be used to display something on the screen is luma.lcd (pip install luma.lcd in venv) and class luma.lcd.device.st7789. Link to documentation: https://luma-core.readthedocs.io/en/latest/interface.html#luma.core.interface.serial.spi
