### ISSUE TITLE
Project the settings shared wirh mobile app and device

### ISSUE THREAD

**Issue by esesyn01** [Mini-air-quality-station/issues#25]
**Goal of the task:**

Do a research how options and configuration will be stored, loaded and modified from both the device and mobile application.

**What functionality will it affect?**

server, system-image

**Scope of the task:**

**Resources and tips:**

The required settings and options are:
- changing the frequency of measurements,
- changing the frequency of switching screens,
- poweroff/reboot
- what will be measured (only p.m gases, temperature or all)
- if you will have any other/new ideas, you can add them

**Definition of Done:**

- Report in a comment in this issue

**Comment by punfil** [comment]
changing the frequency of measurements, -> added to configuration website
changing the frequency of switching screens, -> I am sorry, but I don't understand what you meant here...
poweroff/reboot -> added to configuration website
what will be measured (only p.m gases, temperature or all) -> Already included in Grafana as discussed earlier
