### ISSUE TITLE
Create a list of dependencies for server and mobile-app

### ISSUE THREAD

**Issue by esesyn01** [Mini-air-quality-station/issues#28]
**Goal of the task:**

Create a list of dependencies for server and mobile-app (e.g. packages, python or other libraries, frameworks)

**What functionality will it affect?**

server, mobile-app

**Scope of the task:**

**Resources and tips:**

**Definition of Done:**

- List with dependecies in a comment.

**Comment by punfil** [comment]
- InfluxDB database and it's config,
- Grafana and it's config,
- nginx web server and it's config and files,
- PHP (and php-fpm),
- pyyaml (python3-pyyaml),
- json (python3),
- configparser (python3).

grafana-server.service
influxdb.service

**Comment by esesyn01** [comment]
Thanks for the list, it will be used in the future
